spring:
  datasource:
    url: jdbc:h2:mem:midasdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  h2:
    console:
      enabled: true
      path: /h2-console
  
# Kafka configuration (adjust the topic name as needed)
kafka:
  topic: your-topic

server:
  port: 33400